### ISSUE TITLE
Add to Packagist

### ISSUE THREAD

**Issue by mikeselander** [humanmade/post-cloner#15]

**Comment by tareiking** [comment]
I was hoping to make this a reality, however - the current `master` is failing coding standards / CI (due to #14 ) so I'm not confident I could mark a release version to use with packagist.

I'll be using the repo as a sub-module for the time-being, but watching intently for this to occur - or available to help if this gets bumped.

**Comment by pdewouters** [comment]
Fixed: https://packagist.org/packages/humanmade/post-cloner
